/**
 * One-off: converts the sub-zone pixel rects (`const GEO=...;`) of the relocation demo into image
 * percentages and writes src/data/subAreas.ts. Only GEO is extracted; the demo's IMG/RAW are not read out.
 * Also prints sub-zones that extend more than 1% outside their major-area polygon.
 *
 * Run (Node >= 22.18, native type stripping): node scripts/convertDemoGeo.ts [path/to/demo.html]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  areaBounds,
  FLOOR1_GUIDE_AREAS,
  FLOOR1_MOLD_AREAS,
  FLOOR1_PRESS_AREAS,
  FLOOR1_WAREHOUSE_AREAS,
  FLOOR2_ALL_AREAS,
  pxRectToArea,
  type MapArea,
} from '../src/data/mapAreas.ts'

type Rect = [number, number, number, number]
interface GeoFloor {
  img: string
  w: number
  h: number
  zones: Record<string, Rect>
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const demoPath = resolve(root, process.argv[2] ?? 'docs/Demo___Machine_Relocation_Request.html')
const outPath = resolve(root, 'src/data/subAreas.ts')
const TOLERANCE = 1

/** Demo floor key -> layout id in FLOORS. */
const KEY_TO_LAYOUT: Record<string, string> = {
  'Fac_A|1F': 'floor1', // Floor 1 - Press
  'Fac_B|1F': 'floor2', // Floor 1 - Guide
  'Fac_A|2F': 'floor5', // Floor 2 - All
}
const LAYOUT_IDS = ['floor1', 'floor2', 'floor3', 'floor4', 'floor5']
const MAJOR_AREAS: Record<string, MapArea[]> = {
  floor1: FLOOR1_PRESS_AREAS,
  floor2: FLOOR1_GUIDE_AREAS,
  floor3: FLOOR1_WAREHOUSE_AREAS,
  floor4: FLOOR1_MOLD_AREAS,
  floor5: FLOOR2_ALL_AREAS,
}

const match = /const GEO=(\{.*?\});\s*$/m.exec(readFileSync(demoPath, 'utf8'))
if (!match) throw new Error(`const GEO=...; not found in ${demoPath}`)
const geo = JSON.parse(match[1]) as Record<string, GeoFloor>

const natural = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true })
const out: Record<string, MapArea[]> = Object.fromEntries(LAYOUT_IDS.map((id) => [id, []]))
const deviations: string[] = []

for (const [key, floor] of Object.entries(geo)) {
  const layoutId = KEY_TO_LAYOUT[key]
  if (!layoutId) throw new Error(`Unmapped GEO key: ${key}`)
  // Sub-zones only ("A1-1"); single major areas (A7, A9, ...) already have polygons in mapAreas.
  for (const code of Object.keys(floor.zones).filter((c) => c.includes('-')).sort(natural)) {
    const area = pxRectToArea(code, floor.zones[code], floor.w, floor.h)
    out[layoutId].push(area)
    const major = MAJOR_AREAS[layoutId].find((a) => a.code === code.split('-')[0])
    if (!major) {
      deviations.push(`${layoutId} ${code}: no major-area polygon`)
      continue
    }
    const s = areaBounds(area)
    const m = areaBounds(major)
    const over = Math.max(m.left - s.left, s.right - m.right, m.top - s.top, s.bottom - m.bottom)
    if (over > TOLERANCE) deviations.push(`${layoutId} ${code}: ${over.toFixed(2)}% outside ${major.code}`)
  }
}

const fmt = (a: MapArea) => {
  const b = areaBounds(a)
  return `    rectArea('${a.code}', ${b.left}, ${b.top}, ${b.right}, ${b.bottom}),`
}
const body = LAYOUT_IDS.map((id) => (out[id].length ? `  ${id}: [\n${out[id].map(fmt).join('\n')}\n  ],` : `  ${id}: [],`)).join('\n')
writeFileSync(
  outPath,
  `// GENERATED by scripts/convertDemoGeo.ts from the relocation demo's GEO (pixel rects -> image %). Do not edit by hand.
import { rectArea, type MapArea } from './mapAreas'

/** Sub-zone boundaries per layout id, in the same image-% space as FLOORS areas/zones. */
export const SUB_AREAS: Record<'floor1' | 'floor2' | 'floor3' | 'floor4' | 'floor5', MapArea[]> = {
${body}
}
`,
)

console.log(`Wrote ${outPath}: ${LAYOUT_IDS.map((id) => `${id}=${out[id].length}`).join(', ')}`)
console.log(deviations.length ? `Sub-zones > ${TOLERANCE}% outside major area:\n  ${deviations.join('\n  ')}` : `No sub-zone > ${TOLERANCE}% outside its major area.`)
